### ISSUE TITLE
Redundant dependency

### ISSUE THREAD

**Issue by BulatDashiev** [bence-toth/react-hook-on-mount#2]
'effect' function doesn't need to be in dependency array

**Comment by bence-toth** [comment]
I don't think that's right. Could you please elaborate?

**Comment by BulatDashiev** [comment]
Whatever `effect` is passed passed as argument will be called only once, if `useEffect` called again because of changed `effect` argument it will fall in else block essentially being `noop` operation. Which is the same as `useEffect` without arguments.
Hope I was clear here.

**Comment by bence-toth** [comment]
That is correct.

However, since `effect` is being used inside the `useEffect`, omitting it from the dependency array would be in violation of [the recommendation in the React docs](https://reactjs.org/docs/hooks-reference.html#conditionally-firing-an-effect) (see the note), as well as in violation of a check of the [`eslint-plugin-react-hooks`](https://www.npmjs.com/package/eslint-plugin-react-hooks#installation) ESLint plugin's [`exhaustive-deps`](https://github.com/facebook/react/issues/14920) rule.

So I'd prefer keeping the implementation as-is, even though the `useEffect` would in some cases run and just do nothing.
